services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data

  get_data:
    build:
      context: .
      dockerfile: Dockerfile.get_data
    container_name: get_data
    depends_on:
      - db

  print_data:
    build:
      context: .
      dockerfile: Dockerfile.print_data
    container_name: print_data
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

volumes:
  local_pgdata:
